# Site settings
title: Alamo Tech Collective - San Antonio's Premier Tech Hackerspace
email: ""
description: >-
  San Antonio's premier tech-exclusive hackerspace and makerspace. 24/7 access, 
  high-speed internet, and collaborative workspace for developers, programmers, 
  and digital creators. Join our thriving tech community today.
tagline: "Where San Antonio's Tech Community Collaborates and Innovates"
locale: "en_US"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alamo-tech-collective.github.io" # the base hostname & protocol for your site
github_username: alamo-tech-collective

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CLAUDE.md